### ISSUE TITLE
how to know/ensure the attitude (quaternion) ground truth(s) are correct

### ISSUE THREAD

**Issue by uncleyoung** [uzh-rpg/uzh_fpv_open#11]
Thanks a lot for your work on this dataset. After reading your website and pdf doc, I have a question:
Position ground truth can be checked by compare with the samples of leica/MRP122 system.
How can I know/ensure the attitude ground truth are accurate ? Except for projecting virtual points, which is “quantitatively inaccurate”

**Comment by gcioffi** [comment]
Hi,
the ground truth has been generated via a full batch optimization approach that simultaneously optimizes visual, inertial, and Leica station error terms. The approach is based on: https://rpg.ifi.uzh.ch/docs/RAL2021_Cioffi.pdf

The virtual points are a qualitative evaluation. A quantitative evaluation would require a ground truth, which is obviously not available.

I will close this issue. Feel free to reopen it if you have further questions.
