### ISSUE TITLE
Chrome - cannot download any dataset files

### ISSUE THREAD

**Issue by Caveats** [uzh-rpg/uzh_fpv_open#6]
Load - https://fpv.ifi.uzh.ch/datasets/

Click on Dataset file URL. - Download link. 
Website briefly loads url (in activity) but won't allow download. 

Works on Firefox - but Chrome rejects / won't complete on any of those links. 
Also attempted in Incongnito & on a chromium open (ie no adblockers / etc). 

Appears Chrome won't open those links at all. 
Go Firefox! 

J

**Comment by walchko** [comment]
same problem ... used `wget` to grab the data
